# Generated by Django 5.2.8 on 2025-11-25 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowings', '0003_alter_borrowing_borrow_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=7)),
                ('type', models.CharField(choices=[('PAYMENT', 'Payment for borrowing'), ('FINE', 'Fine for overdue borrowing')], default='PAYMENT', max_length=7)),
                ('session_url', models.URLField(max_length=255)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('money_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrowing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='borrowings.borrowing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
