# Generated by Django 5.2.8 on 2025-11-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='session_url',
            field=models.URLField(max_length=500),
        ),
    ]
