# Generated by Django 5.2.8 on 2025-11-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrow_date',
            field=models.DateField(auto_now_add=True, verbose_name='Borrow date'),
        ),
    ]
