# Generated by Django 5.2.8 on 2025-11-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0004_alter_borrowing_borrow_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(
                auto_now_add=True, verbose_name="Borrow date"
            ),
        ),
    ]
